### ISSUE TITLE
Template height adaptive?

### ISSUE THREAD

**Issue by shenglingshi** [jogibear9988/CodeReason.Reports#3]
Can I make the template height auto adapt content?

**Comment by oshelton** [comment]
This library still wraps WPF's FLowDocument, and it doesn't support that sort of thing.  You might could use a BlockUIContainer to add normal framework elements such as a ViewBox which scales content to fit within the allocated space, but you'll lose the ability to use CodeReason.Reports stuff.  At least I think.

**Comment by jogibear9988** [comment]
I close this, since oshelton sais it's not possible (and i don't know it), so...

**Comment by shenglingshi** [comment]
Ok,I have modify source code.Now,it can auto Calculate height through paragraph or tablecell LineHeight property.
