### ISSUE TITLE
It's a Bug?

### ISSUE THREAD

**Issue by shenglingshi** [jogibear9988/CodeReason.Reports#4]
When a get a FlowDocument object by CreateFlowDocument method。the ReportData no fill document?

**Comment by jogibear9988** [comment]
Don't know. Maybe you can post example code?

**Comment by shenglingshi** [comment]
using (var workspace = new ReportWorkspace(Environment.CurrentDirectory))
{
      var reportDocument = workspace.LoadReport(@"Templates\SimpleReport.xaml");
       ReportData data = new ReportData();
       DataTable table = new DataTable("Ean");
       table.Columns.Add("Position", typeof(string));
       table.Columns.Add("Item", typeof(string));
       table.Columns.Add("EAN", typeof(string));
       table.Columns.Add("Count", typeof(int));
       Random rnd = new Random(1234);
       for (int i = 1; i <= 500; i++)
       {
             table.Rows.Add(new object[] { i, "Item " + i.ToString("0000"), "123456790123", rnd.Next(9) + 1 });
        }
       data.DataTables.Add(table);
       //the flowDocument no fill table data?
       var flowDocument=reportDocument.createFlowDocument();
}

**Comment by shenglingshi** [comment]
Please help me resolve.

**Comment by jogibear9988** [comment]
If implemented a new function that works, but you can't run it in background thread!

**Comment by shenglingshi** [comment]
So,How to get a FlowDocument object with fill data?
there i find a bug:
 if (res.PageHeight == double.NaN)
 it will not equeal never.

**Comment by shenglingshi** [comment]
I just want the printer print page height is equals FlowDocument height,but standard A4 height.
