### ISSUE TITLE
Hi! I'm very interested in this project

### ISSUE THREAD

**Issue by SuperJMN** [jogibear9988/CodeReason.Reports#6]
But I would like to know if it's possible to generate the template of the FlowDocument dynamically. I know it might be tricky :)

**Comment by jogibear9988** [comment]
Why should this not be possible? The Template is loaded from a FileName at the Moment, but it would be easy to implement a function wich loads it from a Stream or a String....

In report workspace you have 

public ReportDocument LoadReport(string fileName)
        {
            if (!File.Exists(fileName))
            {
                throw new FileNotFoundException("Missing report file in specified path", fileName);
            }

```
        var reportDocument = new ReportDocument();

        var reader = new StreamReader(new FileStream(fileName, FileMode.Open, FileAccess.Read));
        reportDocument.XamlData = reader.ReadToEnd();
        reportDocument.XamlImagePath = this.TemplateDirectory;
        reader.Close();

        return reportDocument;
    }
```

if you now implement a new one:

public ReportDocument LoadReport(Stream stream)
        {
            var reportDocument = new ReportDocument();
            var reader = new StreamReader(stream);
            reportDocument.XamlData = reader.ReadToEnd();
            reportDocument.XamlImagePath = this.TemplateDirectory;
            reader.Close();

```
        return reportDocument;
    }
```

maybe i can include this next week (if i didn't forget it!), or you create a fork, implement it and create a pull request!
